# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-XPIDL
version:      0.20
version_from: lib/CORBA/XPIDL.pm
installdirs:  site
requires:
    CORBA::IDL:                    2.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
